api_platform:
    title: TTFL-Seeker
    path_segment_name_generator: api_platform.metadata.path_segment_name_generator.dash
    defaults:
        pagination_client_enabled: true
        pagination_client_items_per_page: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
