name: CI/CD

on: [push]

jobs:
    php:
        runs-on: ubuntu-latest
        container:
            image: airbair/php:ttfl
            credentials:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
        services:
            mariadb:
                image: mariadb
                env:
                    MARIADB_DATABASE: ttfl_test
                    MARIADB_USER: ttfl
                    MARIADB_ROOT_PASSWORD: ttfl
                    MARIADB_PASSWORD: ttfl
                options: --health-cmd="mariadb-admin ping" --health-interval=10s --health-timeout=5s --health-retries=5
        env:
            APP_ENV: test
            DATABASE_URL: "mysql://ttfl:ttfl@mariadb:3306/ttfl?serverVersion=11.0.2-MariaDB&charset=utf8mb4"
        steps:
            - uses: actions/checkout@v2
            - uses: actions/cache@v1
              with:
                path: vendor
                key: composer-${{ hashFiles('**/composer.lock') }}
            - run: composer install
            - run: php vendor/bin/php-cs-fixer fix --dry-run --diff
            - run: php vendor/bin/phpstan analyse --memory-limit=1G
            - run: php bin/phpunit
    yarn:
        runs-on: ubuntu-latest
        container: node:alpine
        steps:
            - uses: actions/checkout@v2
            - uses: actions/cache@v1
              with:
                path: node_modules
                key: yarn-${{ hashFiles('**/yarn.lock') }}
            - run: yarn install
            - run: yarn lint
            - run: yarn build

